# Generated by Django 4.2.8 on 2023-12-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
